food = input("A type of food: ")
plant = input("A type of plant: ")
cooking = input("A method of cooking: ")
burned = input("A word to describe burned food: ")
item = input("A household item: ")
print()
print(cooking, food, "with", burned, plant, "on a bed of", item)